version: "3"
services:
  postgres4:
    image: postgres
    container_name: postgres4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
    restart: unless-stopped
    networks:
      - rest

  rest:
    image: rest:latest
    container_name: rest
    expose:
      - 8079
    ports:
      - 8079:8079
    restart: unless-stopped
    depends_on:
      - postgres4
    links:
      - postgres4
    networks:
      - rest
      - front

  front:
    image: front:latest
    container_name: front
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - rest
    networks:
      - front
      - rest
volumes:
  postgres-data:

networks:
  rest:
  front:
